# Chief engineers / project leads — the people who made the cars WORK.
# Hand-compiled from documented attributions (Wikipedia articles, published
# interviews, marque histories). Deliberately conservative: only people with a
# clearly documented chief-engineer / project-lead / technical-director role on
# the specific car. Design-side people live in d_people.DESIGNERS; a few
# engineer-auteurs (Chapman, Murray, Issigonis…) rightly appear in both layers.
#
# ENGINEERS: name -> (kind, born, died, country, one-line note)
# MODEL_ENGINEERS: (wikipedia_title_of_car, engineer_name, optional_role_note)
#   matched against model nodes by wp title (case/diacritic-insensitive);
#   entries that fail to match are reported by build_data.py.

ENGINEERS = {
    # ---------------- Britain ----------------
    "Colin Chapman": ("person", 1928, 1982, "United Kingdom", "Lotus founder — add lightness"),
    "Mike Kimberley": ("person", 1938, 2024, "United Kingdom", "Lotus engineering chief, later CEO"),
    "Richard Rackham": ("person", None, None, "United Kingdom", "Lotus Elise extruded-aluminium chassis"),
    "Roger Becker": ("person", 1945, 2017, "United Kingdom", "Lotus ride-and-handling institution"),
    "Spen King": ("person", 1925, 2010, "United Kingdom", "Rover gas-turbines to Range Rover"),
    "Gordon Bashford": ("person", 1916, 1991, "United Kingdom", "Land Rover and Range Rover layouts"),
    "William Heynes": ("person", 1903, 1989, "United Kingdom", "Jaguar chief engineer — XK engine, E-Type"),
    "Bob Knight": ("person", 1919, 2000, "United Kingdom", "Jaguar refinement master — XJ ride"),
    "Jim Randle": ("person", 1938, 2019, "United Kingdom", "Jaguar engineering director — XJ220"),
    "Tadek Marek": ("person", 1908, 1982, "Poland", "Aston Martin's great engine designer"),
    "Roy Lunn": ("person", 1925, 2017, "United Kingdom", "GT40 and the Jeep XJ — twice a legend"),
    "Eric Broadley": ("person", 1928, 2017, "United Kingdom", "Lola founder; Mk6 seeded the GT40"),
    "Gordon Murray": ("person", 1946, None, "South Africa", "F1 engineer-auteur — McLaren F1, T.50"),
    "Alec Issigonis": ("person", 1906, 1988, "United Kingdom", "Mini and 1100 — packaging genius"),
    "Charles Spencer 'Spen' King": ("person", 1925, 2010, "United Kingdom", None),  # alias guard, unused
    "George Turnbull": ("person", 1926, 1992, "United Kingdom", "Ex-BL chief who built Hyundai's Pony"),
    "Harry Webster": ("person", 1917, 2007, "United Kingdom", "Triumph chief engineer — Herald to Stag"),
    "Charles Griffin": ("person", 1918, 2000, "United Kingdom", "BMC development chief — 1100/1800"),
    "Peter Wheeler": ("person", 1943, 2009, "United Kingdom", "TVR owner-engineer of the wild era"),
    "Mike Loasby": ("person", 1939, None, "United Kingdom", "Aston V8 development, DeLorean engineering"),
    "David Twohig": ("person", None, None, "Ireland", "A110 revival chief engineer; Zoe, QX30"),
    "Matt Becker": ("person", 1966, None, "United Kingdom", "Elise/Evora handling, then Aston chassis"),
    "Neil Simpson": ("person", None, None, "United Kingdom", "Subaru/Prodrive rally engineering"),

    # ---------------- Germany ----------------
    "Rudolf Uhlenhaut": ("person", 1906, 1989, "Germany", "300 SL and the racing Silver Arrows"),
    "Béla Barényi": ("person", 1907, 1997, "Austria", "Mercedes safety patriarch — crumple zones"),
    "Erich Waxenberger": ("person", 1931, 2017, "Germany", "300 SEL 6.3 — the first Q-car AMG never built"),
    "Hans Mezger": ("person", 1929, 2020, "Germany", "Porsche flat-six, 917, TAG turbo F1 engine"),
    "Helmuth Bott": ("person", 1925, 1994, "Germany", "Porsche development chief — 959 project"),
    "August Achleitner": ("person", 1955, None, "Germany", "Porsche 911 product line 996→991"),
    "Michael Hölscher": ("person", None, None, "Germany", "Carrera GT project manager"),
    "Roland Kussmaul": ("person", 1947, None, "Germany", "Porsche motorsport whisperer — GT3 genesis"),
    "Norbert Singer": ("person", 1939, None, "Germany", "Porsche Le Mans aero — 956/962"),
    "Ferdinand Piëch": ("person", 1937, 2019, "Austria", "917, quattro, Veyron — willpower as engineering"),
    "Jörg Bensinger": ("person", 1939, None, "Germany", "Proposed quattro AWD from the Iltis"),
    "Walter Treser": ("person", 1940, None, "Germany", "First Audi quattro project director"),
    "Roland Gumpert": ("person", 1944, None, "Germany", "Audi Sport AWD rally era; later Apollo"),
    "Wolfgang Schreiber": ("person", None, None, "Germany", "Veyron drivetrain — the DSG and the W16"),
    "Ulrich Bez": ("person", 1943, None, "Germany", "BMW Z1 skunkworks, later Aston CEO"),
    "Ulrich Kranz": ("person", 1957, None, "Germany", "BMW project i — i3/i8 architecture"),
    "Paul Rosche": ("person", 1934, 2016, "Germany", "BMW M engines — S14 to the F1 V12"),
    "Albert Biermann": ("person", 1957, None, "Germany", "BMW M development, then Hyundai N"),
    "Klaus Fritzinger": ("person", None, None, "Germany", "BMW 2002 turbo development"),

    # ---------------- Italy ----------------
    "Gian Paolo Dallara": ("person", 1936, None, "Italy", "Miura chassis; the racecar house that followed"),
    "Paolo Stanzani": ("person", 1936, 2017, "Italy", "Countach engineering; EB110 concept"),
    "Bob Wallace": ("person", 1938, 2013, "New Zealand", "Lamborghini development driver-engineer"),
    "Massimo Ceccarani": ("person", None, None, "Italy", "Lamborghini technical director — Murciélago era"),
    "Maurizio Reggiani": ("person", 1959, None, "Italy", "Lamborghini R&D chief — Aventador, Huracán"),
    "Nicola Materazzi": ("person", 1939, 2022, "Italy", "Stratos, 288 GTO, F40, EB110 — the great enabler"),
    "Mauro Forghieri": ("person", 1935, 2022, "Italy", "Ferrari racing polymath — flat-12s and wings"),
    "Amedeo Felisa": ("person", 1946, None, "Italy", "Ferrari GT engineering 355→458; later CEO"),
    "Aurelio Lampredi": ("person", 1917, 1989, "Italy", "Ferrari V12s, then Fiat's immortal twin-cam"),
    "Dante Giacosa": ("person", 1905, 1996, "Italy", "Fiat's engineering conscience — 500 to 128"),
    "Oscar Montabone": ("person", 1921, 1994, "Italy", "Fiat 124 chief engineer"),
    "Orazio Satta Puliga": ("person", 1910, 1974, "Italy", "Alfa Romeo — Giulietta and Giulia"),
    "Giuseppe Busso": ("person", 1913, 2006, "Italy", "The Busso V6 — Alfa's singing engine"),
    "Carlo Chiti": ("person", 1924, 1994, "Italy", "Alfa/ATS racing engines, Autodelta"),
    "Sergio Limone": ("person", 1948, None, "Italy", "Abarth — 037, Delta S4, Integrale evolutions"),
    "Mike Parkes": ("person", 1931, 1977, "United Kingdom", "Ferrari racer-engineer; Stratos development"),
    "Giotto Bizzarrini": ("person", 1926, 2023, "Italy", "250 GTO, Lamborghini V12, his own 5300 GT"),
    "Gioacchino Colombo": ("person", 1903, 1988, "Italy", "The original Ferrari V12"),
    "Vittorio Jano": ("person", 1891, 1965, "Italy", "Alfa/Lancia master — Dino V6 patriarch"),

    # ---------------- France ----------------
    "André Lefèbvre": ("person", 1894, 1964, "France", "Citroën Traction, 2CV, DS — aviation thinking"),
    "Paul Magès": ("person", 1908, 1999, "France", "Citroën hydropneumatics — DS/SM suspension"),
    "Jean Rédélé": ("person", 1922, 2007, "France", "Alpine founder — Dieppe's giant-killers"),
    "Philippe Guédon": ("person", 1933, 2020, "France", "Matra — father of the Espace"),
    "Georges Douin": ("person", None, None, "France", "Renault turbo era engineering"),
    "François Castaing": ("person", 1945, 2023, "France", "AMC/Chrysler engineering — XJ, LH, Viper program"),

    # ---------------- Japan ----------------
    "Jiro Kawano": ("person", 1922, None, "Japan", "Toyota 2000GT project father"),
    "Tatsuo Hasegawa": ("person", 1916, 2008, "Japan", "Corolla chief engineer — aircraft aero roots"),
    "Nobuaki Katayama": ("person", None, None, "Japan", "AE86 chief engineer; later Altezza"),
    "Isao Tsuzuki": ("person", None, None, "Japan", "A80 Supra chief engineer"),
    "Takeshi Uchiyamada": ("person", 1946, None, "Japan", "Prius chief engineer — hybrid paradigm"),
    "Tetsuya Tada": ("person", 1957, None, "Japan", "86/GR Supra chief engineer"),
    "Haruhiko Tanahashi": ("person", None, None, "Japan", "LFA chief engineer — a decade of carbon"),
    "Naohiko Saito": ("person", None, None, "Japan", "GR Yaris chief engineer — homologation reborn"),
    "Ichiro Suzuki": ("person", None, None, "Japan", "Lexus LS400 chief engineer — the flagship F1 project"),
    "Yoshikazu Ishii": ("person", None, None, "Japan", "Land Cruiser 80 development"),
    "Shigeru Uehara": ("person", 1947, None, "Japan", "Honda NSX, Type R line, S2000"),
    "Shinya Iwakura": ("person", None, None, "Japan", "Honda S2000 later development"),
    "Soichiro Honda": ("person", 1906, 1991, "Japan", "Founder-engineer — the S-cars and the dream"),
    "Tadashi Kume": ("person", 1932, 2022, "Japan", "Honda CVCC engine; later president"),
    "Shinichiro Sakurai": ("person", 1929, 2011, "Japan", "Skyline's lifelong chief — Prince to R30"),
    "Naganori Ito": ("person", None, None, "Japan", "R32 Skyline GT-R chief engineer"),
    "Kozo Watanabe": ("person", None, None, "Japan", "R33/R34 Skyline GT-R chief engineer"),
    "Kazutoshi Mizuno": ("person", 1952, None, "Japan", "R35 GT-R — 'Mr. GT-R'"),
    "Yutaka Katayama": ("person", 1909, 2015, "Japan", "'Mr. K' — the 240Z's champion"),
    "Kenichi Yamamoto": ("person", 1922, 2017, "Japan", "Mazda rotary program — 47 samurai"),
    "Toshihiko Hirai": ("person", 1935, None, "Japan", "MX-5 NA chief engineer — jinba ittai"),
    "Takaharu Kobayakawa": ("person", 1943, None, "Japan", "RX-7 FD chief engineer"),
    "Shinroku Momose": ("person", 1919, 1997, "Japan", "Subaru 360 and 1000 — boxer beginnings"),
    "Naoyuki Sakamoto": ("person", None, None, "Japan", "GR Corolla chief engineer"),

    # ---------------- United States ----------------
    "Zora Arkus-Duntov": ("person", 1909, 1996, "Belgium", "Corvette's godfather-engineer"),
    "Dave McLellan": ("person", 1936, None, "United States", "Corvette C4 chief engineer"),
    "Dave Hill": ("person", 1943, None, "United States", "Corvette C5/C6 chief engineer"),
    "Tadge Juechter": ("person", 1956, None, "United States", "Corvette C7/C8 — mid-engine at last"),
    "Ed Cole": ("person", 1909, 1977, "United States", "Chevy small-block V8; Corvair father"),
    "John DeLorean": ("person", 1925, 2005, "United States", "Pontiac GTO, then his own dream"),
    "Bill Collins": ("person", 1932, None, "United States", "DMC-12 chief engineer, GTO development"),
    "Donald Frey": ("person", 1923, 2010, "United States", "Mustang product planner-engineer"),
    "Carroll Shelby": ("person", 1923, 2012, "United States", "Cobra — chicken farmer, Le Mans winner"),
    "Roy Sjoberg": ("person", 1938, None, "United States", "Viper chief engineer — Team Viper"),
    "Herb Adams": ("person", 1940, None, "United States", "Pontiac Trans Am handling"),
    "Peter Rawlinson": ("person", 1957, None, "United Kingdom", "Model S chief engineer, then Lucid Air"),
    "JB Straubel": ("person", 1975, None, "United States", "Tesla CTO — battery architecture"),
    "John Z. DeLorean": ("person", 1925, 2005, "United States", None),  # alias guard, unused

    # ---------------- rest of world ----------------
    "Ferry Porsche": ("person", 1909, 1998, "Austria", "356 — the son who built the company"),
    "Mate Rimac": ("person", 1988, None, "Croatia", "Garage BMW EV to Nevera — founder-engineer"),
    "Christian von Koenigsegg": ("person", 1972, None, "Sweden", "Founder-engineer — camless dreams"),
    "Erik Carlsson": ("person", 1929, 2015, "Sweden", None),  # alias guard, unused
    "Per Gillbrand": ("person", 1934, 2016, "Sweden", "Saab turbocharging — the 99/900 Turbo"),
    "Paul Frère": ("person", 1917, 2008, "Belgium", None),  # alias guard, unused
}

# (car wikipedia title, engineer, role shown in the UI)
MODEL_ENGINEERS = [
    # Lotus / Chapman world
    ("Lotus Seven", "Colin Chapman", "designed and engineered"),
    ("Lotus Elan", "Colin Chapman", "project lead"),
    ("Lotus Elite", "Colin Chapman", "project lead"),
    ("Lotus Europa", "Colin Chapman", "project lead"),
    ("Lotus Esprit", "Mike Kimberley", "chief engineer"),
    ("Lotus Esprit", "Colin Chapman", "project lead"),
    ("Lotus Elise", "Richard Rackham", "chassis engineer"),
    ("Lotus Elise", "Roger Becker", "ride & handling"),
    ("Lotus Evora", "Matt Becker", "vehicle dynamics"),
    ("Caterham 7", "Colin Chapman", "original design"),

    # Britain
    ("Range Rover", "Spen King", "chief engineer"),
    ("Range Rover", "Gordon Bashford", "layout engineer"),
    ("Range Rover Classic", "Spen King", "chief engineer"),
    ("Rover SD1", "Spen King", "chief engineer"),
    ("Triumph Herald", "Harry Webster", "chief engineer"),
    ("Triumph Spitfire", "Harry Webster", "chief engineer"),
    ("Triumph TR4", "Harry Webster", "chief engineer"),
    ("Triumph Stag", "Harry Webster", "chief engineer"),
    ("Triumph 2000", "Harry Webster", "chief engineer"),
    ("Jaguar E-Type", "William Heynes", "chief engineer"),
    ("Jaguar Mark 2", "William Heynes", "chief engineer"),
    ("Jaguar XJ (Series 1, 2 and 3)", "Bob Knight", "development chief"),
    
    
    ("Jaguar XJ220", "Jim Randle", "concept engineering director"),
    ("Aston Martin DB4 GT Zagato", "Tadek Marek", "engine designer"),
    ("Aston Martin DB5", "Tadek Marek", "engine designer"),
    ("Aston Martin DB6", "Tadek Marek", "engine designer"),
    ("Aston Martin V8", "Tadek Marek", "engine designer"),
    ("Ford GT40", "Roy Lunn", "chief engineer"),
    ("Ford GT40", "Eric Broadley", "Lola Mk6 basis"),
    ("Jeep Cherokee (XJ)", "Roy Lunn", "chief engineer"),
    ("Jeep Cherokee (XJ)", "François Castaing", "engineering VP"),
    ("McLaren F1", "Gordon Murray", "designed and engineered"),
    ("McLaren F1", "Paul Rosche", "S70/2 V12 engine"),
    ("Gordon Murray T.50", "Gordon Murray", "designed and engineered"),
    ("Mini", "Alec Issigonis", "designed and engineered"),
    ("Mini (Mark I)", "Alec Issigonis", "designed and engineered"),
    ("BMC ADO16", "Alec Issigonis", "chief engineer"),
    ("Austin Maxi", "Alec Issigonis", "chief engineer"),
    ("BMC ADO17", "Alec Issigonis", "chief engineer"),
    ("Hyundai Pony", "George Turnbull", "project director"),
    ("TVR Griffith", "Peter Wheeler", "owner-engineer"),
    ("TVR Cerbera", "Peter Wheeler", "owner-engineer"),
    ("TVR Tuscan Speed Six", "Peter Wheeler", "owner-engineer"),
    ("DMC DeLorean", "Bill Collins", "chief engineer"),
    ("DMC DeLorean", "Mike Loasby", "engineering director"),
    ("Alpine A110 (2017)", "David Twohig", "chief engineer"),

    # Germany
    ("Mercedes-Benz 300 SL", "Rudolf Uhlenhaut", "chief engineer"),
    ("Mercedes-Benz W111", "Béla Barényi", "safety architecture"),
    ("Mercedes-Benz W113", "Béla Barényi", "safety architecture"),
    ("Mercedes-Benz W113", "Rudolf Uhlenhaut", "development chief"),
    ("Mercedes-Benz 600", "Rudolf Uhlenhaut", "development chief"),
    ("Mercedes-Benz 300 SEL 6.3", "Erich Waxenberger", "skunkworks creator"),
    ("Porsche 911", "Hans Mezger", "flat-six designer"),
    
    
    ("Porsche 959", "Helmuth Bott", "project lead"),
    ("Porsche 911 (996)", "August Achleitner", "product line director"),
    ("Porsche 911 (997)", "August Achleitner", "product line director"),
    ("Porsche 911 (991)", "August Achleitner", "product line director"),
    ("Porsche Carrera GT", "Michael Hölscher", "project manager"),
    ("Porsche 911 GT3", "Roland Kussmaul", "motorsport development"),
    
    
    ("Audi Quattro", "Jörg Bensinger", "AWD concept"),
    ("Audi Quattro", "Walter Treser", "project director"),
    ("Audi Quattro", "Ferdinand Piëch", "R&D chief"),
    
    ("Bugatti Veyron", "Wolfgang Schreiber", "development head"),
    ("Bugatti Veyron", "Ferdinand Piëch", "the impossible brief"),
    ("BMW Z1", "Ulrich Bez", "BMW Technik project lead"),
    ("BMW i3", "Ulrich Kranz", "project i lead"),
    ("BMW i8", "Ulrich Kranz", "project i lead"),
    ("BMW M1", "Gian Paolo Dallara", "chassis engineering"),
    ("BMW M1", "Paul Rosche", "M88 engine"),
    ("BMW M3", "Paul Rosche", "S14 engine (E30)"),
    ("BMW 2002", "Paul Rosche", "engine development"),
    ("Hyundai i30", "Albert Biermann", "i30 N — N division chief"),
    ("Hyundai Veloster", "Albert Biermann", "Veloster N — N division chief"),
    ("Kia Stinger", "Albert Biermann", "development chief"),

    # Italy
    ("Lamborghini Miura", "Gian Paolo Dallara", "chief engineer"),
    ("Lamborghini Miura", "Paolo Stanzani", "engineering"),
    ("Lamborghini Miura", "Bob Wallace", "development driver"),
    ("Lamborghini Countach", "Paolo Stanzani", "chief engineer"),
    ("Lamborghini Countach", "Bob Wallace", "development driver"),
    ("Lamborghini Espada", "Gian Paolo Dallara", "chief engineer"),
    ("Lamborghini Murciélago", "Massimo Ceccarani", "technical director"),
    ("Lamborghini Aventador", "Maurizio Reggiani", "R&D director"),
    ("Lamborghini Huracán", "Maurizio Reggiani", "R&D director"),
    ("Lancia Stratos", "Nicola Materazzi", "development engineer"),
    ("Lancia Stratos", "Mike Parkes", "development"),
    ("Ferrari 288 GTO", "Nicola Materazzi", "chief engineer"),
    ("Ferrari F40", "Nicola Materazzi", "chief engineer"),
    ("Ferrari Enzo", "Amedeo Felisa", "engineering head"),
    ("Ferrari 458", "Amedeo Felisa", "engineering head"),
    ("Bugatti EB110", "Nicola Materazzi", "technical director"),
    ("Bugatti EB110", "Paolo Stanzani", "initial project"),
    ("Fiat 124", "Aurelio Lampredi", "twin-cam engine"),
    ("Fiat 124", "Oscar Montabone", "chief engineer"),
    ("Fiat 124 Sport Spider", "Aurelio Lampredi", "twin-cam engine"),
    ("Fiat 128", "Dante Giacosa", "engineering director"),
    ("Autobianchi Primula", "Dante Giacosa", "FWD pioneer project"),
    ("Alfa Romeo Giulia", "Orazio Satta Puliga", "chief engineer"),
    ("Alfa Romeo Spider", "Orazio Satta Puliga", "chief engineer"),
    ("Alfa Romeo Alfetta", "Giuseppe Busso", "V6 engine (GTV6)"),
    ("Alfa Romeo 33 Stradale", "Carlo Chiti", "Autodelta engineering"),
    ("Lancia 037", "Sergio Limone", "chief engineer"),
    ("Lancia Delta S4", "Sergio Limone", "chief engineer"),
    ("Lancia Delta", "Sergio Limone", "Integrale evolutions"),
    ("Iso Grifo", "Giotto Bizzarrini", "chassis engineer"),
    
    ("Lamborghini 350 GT", "Giotto Bizzarrini", "V12 designer"),

    # France
    ("Citroën DS", "André Lefèbvre", "chief engineer"),
    ("Citroën DS", "Paul Magès", "hydropneumatics"),
    ("Citroën SM", "Paul Magès", "hydropneumatics"),
    ("Alpine A110", "Jean Rédélé", "founder-engineer"),
    ("Renault Espace", "Philippe Guédon", "Matra project father"),

    # Japan
    ("Toyota 2000GT", "Jiro Kawano", "project chief"),
    ("Toyota Corolla", "Tatsuo Hasegawa", "chief engineer"),
    ("Toyota AE86", "Nobuaki Katayama", "chief engineer"),
    ("Toyota Supra (A80)", "Isao Tsuzuki", "chief engineer"),
    ("Toyota Prius", "Takeshi Uchiyamada", "chief engineer"),
    ("Toyota 86", "Tetsuya Tada", "chief engineer"),
    ("Toyota GR Supra", "Tetsuya Tada", "chief engineer"),
    ("Lexus LFA", "Haruhiko Tanahashi", "chief engineer"),
    ("Toyota GR Yaris", "Naohiko Saito", "chief engineer"),
    ("Toyota GR Corolla", "Naoyuki Sakamoto", "chief engineer"),
    ("Lexus LS", "Ichiro Suzuki", "chief engineer, F1 project"),
    ("Honda NSX", "Shigeru Uehara", "chief engineer"),
    ("Honda S2000", "Shigeru Uehara", "chief engineer"),
    ("Honda Integra", "Shigeru Uehara", "Type R program"),
    ("Honda S500", "Soichiro Honda", "founder-engineer"),
    ("Honda S600", "Soichiro Honda", "founder-engineer"),
    ("Honda S800", "Soichiro Honda", "founder-engineer"),
    ("Honda Civic", "Tadashi Kume", "CVCC engine"),
    ("Nissan Skyline GT-R", "Shinichiro Sakurai", "Skyline dynasty patriarch"),
    ("Nissan Skyline GT-R", "Naganori Ito", "R32 chief engineer"),
    ("Nissan GT-R", "Kazutoshi Mizuno", "chief engineer"),
    ("Nissan Z-car", "Yutaka Katayama", "project champion"),
    ("Nissan S30", "Yutaka Katayama", "project champion"),
    ("Mazda Cosmo", "Kenichi Yamamoto", "rotary program chief"),
    ("Mazda MX-5", "Toshihiko Hirai", "chief engineer"),
    ("Mazda MX-5 (NA)", "Toshihiko Hirai", "chief engineer"),
    ("Mazda RX-7", "Takaharu Kobayakawa", "FD chief engineer"),
    ("Subaru 360", "Shinroku Momose", "chief engineer"),
    ("Subaru 1000", "Shinroku Momose", "chief engineer"),

    # United States
    ("Chevrolet Corvette (C2)", "Zora Arkus-Duntov", "chief engineer"),
    ("Chevrolet Corvette (C3)", "Zora Arkus-Duntov", "chief engineer"),
    ("Chevrolet Corvette (C4)", "Dave McLellan", "chief engineer"),
    ("Chevrolet Corvette (C5)", "Dave Hill", "chief engineer"),
    ("Chevrolet Corvette (C6)", "Dave Hill", "chief engineer"),
    ("Chevrolet Corvette (C7)", "Tadge Juechter", "chief engineer"),
    ("Chevrolet Corvette (C8)", "Tadge Juechter", "chief engineer"),
    ("Chevrolet Corvair", "Ed Cole", "program father"),
    ("Pontiac GTO", "John DeLorean", "chief engineer"),
    ("Pontiac Firebird", "Herb Adams", "handling development"),
    ("Ford Mustang", "Donald Frey", "product manager-engineer"),
    ("AC Cobra", "Carroll Shelby", "creator"),
    ("Shelby Mustang", "Carroll Shelby", "GT350 program"),
    ("Dodge Viper", "Roy Sjoberg", "chief engineer"),
    ("Dodge Viper", "François Castaing", "engineering VP"),
    ("Tesla Model S", "Peter Rawlinson", "chief engineer"),
    ("Tesla Roadster (first generation)", "JB Straubel", "battery architecture"),
    ("Lucid Air", "Peter Rawlinson", "CEO and chief engineer"),

    # rest of world
    ("Rimac Nevera", "Mate Rimac", "founder-engineer"),
    ("Rimac Concept One", "Mate Rimac", "founder-engineer"),
    ("Koenigsegg CC8S", "Christian von Koenigsegg", "founder-engineer"),
    ("Koenigsegg Jesko", "Christian von Koenigsegg", "founder-engineer"),
    ("Saab 99", "Per Gillbrand", "turbo development"),
    ("Saab 900", "Per Gillbrand", "turbo development"),
    ("Fiat 500", "Dante Giacosa", "designed and engineered"),
    ("Citroën DS", "André Lefèbvre", "chief engineer"),
    ("Porsche 356", "Ferry Porsche", "founder-engineer"),
]


# ---------------- expansion pass 2: the famous names ----------------
ENGINEERS.update({
    "Andreas Preuninger": ("person", None, None, "Germany", "Porsche GT road cars — every GT3 since the 996.2"),
    "Walter Röhrl": ("person", 1947, None, "Germany", "Rally deity turned Porsche development driver"),
    "Ernst Fuhrmann": ("person", 1918, 1995, "Austria", "Four-cam Carrera engine; the 911 Turbo era"),
    "Frank-Steffen Walliser": ("person", None, None, "Germany", "918 Spyder program, later 911 line director"),
    "Hans Scherenberg": ("person", 1910, 2000, "Germany", "Daimler-Benz development chief 1965–77"),
    "Tobias Moers": ("person", 1966, None, "Germany", "AMG development boss, later CEO"),
    "Alex von Falkenhausen": ("person", 1907, 1989, "Germany", "BMW engine patriarch — M10, New Class"),
    "Ludwig Kraus": ("person", 1911, 1997, "Germany", "Audi 100 father — saved Audi's independence"),
    "Ulrich Hackenberg": ("person", 1950, None, "Germany", "VW Group architecture czar — MQB"),
    "Alois Ruf": ("person", 1950, None, "Germany", "Ruf Automobile — the Yellowbird and beyond"),
    "Giulio Alfieri": ("person", 1924, 2002, "Italy", "Maserati chief engineer — Birdcage to Bora"),
    "Luigi Marmiroli": ("person", None, None, "Italy", "Lamborghini Diablo technical director"),
    "Rudolf Hruska": ("person", 1915, 1995, "Austria", "Alfasud project — Alfa's clean-sheet car"),
    "Claudio Zampolli": ("person", 1939, 2021, "Italy", "Cizeta founder — the V16 dream"),
    "Adrian Newey": ("person", 1958, None, "United Kingdom", "F1's greatest aerodynamicist — Valkyrie"),
    "Chris Porritt": ("person", None, None, "United Kingdom", "One-77 chief engineer, later Tesla"),
    "Dan Parry-Williams": ("person", None, None, "United Kingdom", "McLaren road-car design engineering"),
    "Richard Parry-Jones": ("person", 1951, 2021, "United Kingdom", "Ford dynamics guru — the Focus feel"),
    "John Cooper": ("person", 1923, 2000, "United Kingdom", "Cooper Car Company — the hot Mini"),
    "Alex Moulton": ("person", 1920, 2012, "United Kingdom", "Suspension savant — rubber cones, Hydrolastic"),
    "Harry Mundy": ("person", 1915, 1988, "United Kingdom", "Lotus twin-cam, Jaguar V12"),
    "Ron Hickman": ("person", 1932, 2011, "South Africa", "Elan design engineering; invented the Workmate"),
    "Syd Enever": ("person", 1906, 1993, "United Kingdom", "MG chief engineer — MGA and MGB"),
    "Lee Noble": ("person", 1958, None, "United Kingdom", "Noble founder-engineer"),
    "Simon Saunders": ("person", None, None, "United Kingdom", "Ariel Atom creator"),
    "Amédée Gordini": ("person", 1899, 1979, "France", "Le Sorcier — Renault's tuning wizard"),
    "René Bonnet": ("person", 1904, 1983, "France", "DB and René Bonnet — mid-engine pioneer"),
    "Takao Kijima": ("person", None, None, "Japan", "MX-5 program manager, NB and NC"),
    "Nobuhiro Yamamoto": ("person", None, None, "Japan", "787B veteran; MX-5 ND program manager"),
    "Ryo Mukumoto": ("person", None, None, "Japan", "Honda's youngest-ever LPL — the S660"),
    "Hanji Umehara": ("person", None, None, "Japan", "Named and shaped the Land Cruiser"),
    "Hal Sperlich": ("person", 1929, None, "United States", "Mustang and minivan product father"),
    "John Hennessey": ("person", None, None, "United States", "Texas tuner-founder — Venom"),
    "Jerod Shelby": ("person", None, None, "United States", "SSC founder — no relation, all speed"),
    "Steve Saleen": ("person", 1949, None, "United States", "Saleen founder — the S7"),
    "RJ Scaringe": ("person", 1983, None, "United States", "Rivian founder — MIT PhD"),
    "Kevin Czinger": ("person", None, None, "United States", "3D-printed hypercar — the 21C"),
    "Joop Donkervoort": ("person", 1949, None, "Netherlands", "Donkervoort founder"),
    "Rolf Mellde": ("person", 1922, 2004, "Sweden", "Saab's first engineer — the V4 rescue"),
})

MODEL_ENGINEERS += [
    # Porsche GT world
    ("Porsche 911 GT3", "Andreas Preuninger", "GT division boss"),
    ("Porsche 911 GT2", "Andreas Preuninger", "GT division boss"),
    ("Porsche 911 GT3", "Walter Röhrl", "development driver"),
    ("Porsche Carrera GT", "Walter Röhrl", "development driver"),
    ("Porsche 356", "Ernst Fuhrmann", "Carrera four-cam engine"),
    ("Porsche 918 Spyder", "Frank-Steffen Walliser", "project director"),
    # Germany
    ("Mercedes-Benz W116", "Hans Scherenberg", "development chief"),
    ("Mercedes-Benz SLS AMG", "Tobias Moers", "development chief"),
    ("Mercedes-AMG GT", "Tobias Moers", "AMG boss"),
    ("BMW New Class", "Alex von Falkenhausen", "engines & development"),
    ("BMW 2002", "Alex von Falkenhausen", "engine patriarch"),
    ("Audi 100", "Ludwig Kraus", "chief engineer"),
    ("Volkswagen Golf Mk7", "Ulrich Hackenberg", "MQB architecture"),
    ("Ruf CTR", "Alois Ruf", "founder-engineer"),
    ("Gumpert Apollo", "Roland Gumpert", "founder-engineer"),
    # Italy
    ("Maserati Bora", "Giulio Alfieri", "chief engineer"),
    ("Maserati Ghibli", "Giulio Alfieri", "chief engineer"),
    ("Lamborghini Diablo", "Luigi Marmiroli", "technical director"),
    ("Alfa Romeo Alfasud", "Rudolf Hruska", "project director"),
    ("Cizeta-Moroder V16T", "Claudio Zampolli", "founder-engineer"),
    ("Ferrari 250 GTO", "Giotto Bizzarrini", "development chief"),
    ("Ferrari 250 GTO", "Gioacchino Colombo", "V12 architecture"),
    ("De Tomaso Pantera", "Gian Paolo Dallara", "engineering"),
    ("Pagani Zonda", "Horacio Pagani", "composites & construction"),
    # Britain
    ("Aston Martin Valkyrie", "Adrian Newey", "concept & aerodynamics"),
    ("Aston Martin One-77", "Chris Porritt", "chief engineer"),
    ("McLaren MP4-12C", "Dan Parry-Williams", "design engineering director"),
    ("Ford Focus (first generation)", "Richard Parry-Jones", "vehicle dynamics"),
    ("Ford Mondeo (first generation)", "Richard Parry-Jones", "vehicle dynamics"),
    ("Mini", "John Cooper", "Cooper performance versions"),
    ("Mini", "Alex Moulton", "rubber-cone suspension"),
    ("BMC ADO16", "Alex Moulton", "Hydrolastic suspension"),
    ("BMC ADO16", "Charles Griffin", "development chief"),
    ("Lotus Elan", "Harry Mundy", "twin-cam engine"),
    ("Lotus Elan", "Ron Hickman", "design engineering"),
    ("MG MGB", "Syd Enever", "chief engineer"),
    ("Noble M12", "Lee Noble", "founder-engineer"),
    ("Ariel Atom", "Simon Saunders", "creator"),
    ("Gordon Murray Automotive T.33", "Gordon Murray", "designed and engineered"),
    # France
    ("Renault 8", "Amédée Gordini", "Gordini — the giant-killer"),
    ("Matra Djet", "René Bonnet", "creator — first mid-engine road car"),
    # Japan
    ("Mazda MX-5 (NB)", "Takao Kijima", "program manager"),
    ("Mazda MX-5 (NC)", "Takao Kijima", "program manager"),
    ("Mazda MX-5 (ND)", "Nobuhiro Yamamoto", "program manager"),
    ("Nissan Skyline GT-R", "Kozo Watanabe", "R33/R34 chief engineer"),
    ("Honda S660", "Ryo Mukumoto", "large project leader"),
    ("Toyota Land Cruiser (J40)", "Hanji Umehara", "Land Cruiser patriarch"),
    # United States
    ("Ford Mustang", "Hal Sperlich", "product planning"),
    ("Dodge Caravan", "Hal Sperlich", "minivan program father"),
    ("AMC Eagle", "Roy Lunn", "chief engineer — crossover pioneer"),
    ("Hennessey Venom GT", "John Hennessey", "founder"),
    ("SSC Ultimate Aero", "Jerod Shelby", "founder-engineer"),
    ("SSC Tuatara", "Jerod Shelby", "founder-engineer"),
    ("Saleen S7", "Steve Saleen", "founder"),
    ("Rivian R1T", "RJ Scaringe", "founder-engineer"),
    ("Czinger 21C", "Kevin Czinger", "founder"),
    # rest of world
    ("Donkervoort D8", "Joop Donkervoort", "founder-engineer"),
    ("Saab 96", "Rolf Mellde", "engineering chief"),
]

# prune placeholder rows
MODEL_ENGINEERS = [e for e in MODEL_ENGINEERS if e[1]]
# drop alias-guard entries never referenced
_used = {e[1] for e in MODEL_ENGINEERS}
ENGINEERS = {k: v for k, v in ENGINEERS.items() if k in _used}
