# Shared-platform / badge-engineering groups.
# (note, [(make, model name), ...]) — every listed car is pairwise linked within the group.
# All relationships are documented industrial facts (joint development, shared platform, or rebadge).
PLATFORM_GROUPS = [
("Joint Toyota–Subaru sports car (ZN6/ZC6), one car, three badges",
 [("Toyota","86"),("Subaru","BRZ"),("Scion","FR-S")]),
("Toyota–BMW joint development: J29 Supra and G29 Z4 share platform and Austrian assembly line",
 [("Toyota","GR Supra (A90)"),("BMW","Z4 (G29)")]),
("Fiat's revival roadster is built by Mazda in Hiroshima on the ND platform",
 [("Mazda","MX-5 (ND)"),("Fiat","124 Spider (2016)")]),
("NUMMI joint venture twins: GM-badged Toyota Corolla",
 [("Geo","Prizm"),("Toyota","Corolla")]),
("Toyota–GM Voltz/Matrix/Vibe program — same car, two grilles",
 [("Pontiac","Vibe"),("Toyota","Matrix")]),
("Diamond-Star Motors triplets (Mitsubishi–Chrysler joint venture)",
 [("Mitsubishi","Eclipse"),("Eagle","Talon"),("Plymouth","Laser")]),
("Ford–Mazda GD platform coupés from AutoAlliance",
 [("Ford","Probe"),("Mazda","MX-6")]),
("The 'Saabaru' — a re-nosed Impreza built by Subaru for GM-era Saab",
 [("Saab","9-2X"),("Subaru","Impreza WRX")]),
("Crossfire is built on the R170 SLK platform by Karmann",
 [("Chrysler","Crossfire"),("Mercedes-Benz","SLK (R170)")]),
("Lotus Elise architecture: GM's Speedster/VX220 and Tesla's first Roadster both built on it",
 [("Lotus","Elise"),("Opel","Speedster"),("Tesla","Roadster")]),
("DeLorean's backbone chassis was engineered by Lotus from Esprit practice",
 [("DMC","DeLorean"),("Lotus","Esprit")]),
("VW Group MQB platform",
 [("Volkswagen","Golf (Mk7)"),("Audi","A3 (Mk3)"),("SEAT","León (Mk3)"),("Škoda","Octavia (Mk3)")]),
("VW Group NSF city-car triplets, built in Bratislava",
 [("Volkswagen","up!"),("Škoda","Citigo"),("SEAT","Mii")]),
("PSA–Toyota TPCA triplets from Kolín",
 [("Peugeot","107"),("Citroën","C1"),("Toyota","Aygo")]),
("Renault–Daimler rear-engined twins, built in Novo Mesto",
 [("Renault","Twingo III"),("Smart","Forfour")]),
("X-Type rides on an AWD-adapted CD132 Mondeo platform",
 [("Jaguar","X-Type"),("Ford","Mondeo")]),
("DB7 grew out of the XJS platform via the stillborn Jaguar XJ41",
 [("Aston Martin","DB7"),("Jaguar","XJS")]),
("Taurus and Sable — Ford's aero twins",
 [("Ford","Taurus"),("Mercury","Sable")]),
("Fox-body siblings",
 [("Ford","Mustang (Fox)"),("Mercury","Capri (Fox)")]),
("Holden's Monaro exported as the reborn GTO",
 [("Holden","Monaro (V2)"),("Pontiac","GTO (2004)")]),
("Fiat 500 and Ka Mk2 share the Fiat Mini platform and the Tychy line",
 [("Fiat","500 (2007)"),("Ford","Ka (Mk2)")]),
("MC12 is a rebodied Enzo underneath",
 [("Maserati","MC12"),("Ferrari","Enzo")]),
("Sant'Agata and Ingolstadt share an aluminium spaceframe",
 [("Lamborghini","Gallardo"),("Audi","R8")]),
("Second-generation platform sharing continued with the Huracán",
 [("Lamborghini","Huracán"),("Audi","R8")]),
("VW Group PL71 SUV platform",
 [("Porsche","Cayenne"),("Volkswagen","Touareg"),("Audi","Q7")]),
("Continental GT launched on the Phaeton's D1 platform",
 [("Bentley","Continental GT"),("Volkswagen","Phaeton")]),
("PQ34 platform under the Bauhaus coupé and the retro Beetle",
 [("Audi","TT"),("Volkswagen","Golf (Mk4)"),("Volkswagen","New Beetle")]),
("Nissan FM platform siblings",
 [("Nissan","350Z"),("Infiniti","G35")]),
("Camry-based Lexus ES — twins since 1989",
 [("Lexus","ES"),("Toyota","Camry")]),
("GM Kappa roadster trio",
 [("Pontiac","Solstice"),("Saturn","Sky"),("Opel","GT (2007)")]),
("Fifth-gen Camaro rides on Holden's Zeta platform",
 [("Chevrolet","Camaro (5th gen)"),("Holden","Commodore (VE)")]),
("Merak borrowed the SM's V6, dash and front end",
 [("Maserati","Merak"),("Citroën","SM")]),
("R5 Turbo: the shopping car turned mid-engine Group B weapon",
 [("Renault","5"),("Renault","5 Turbo")]),
("VW A1 platform family",
 [("Volkswagen","Golf (Mk1)"),("Volkswagen","Scirocco"),("Volkswagen","Jetta")]),
("VW B1 platform: Passat is a fastback Audi 80",
 [("Audi","80 (B1)"),("Volkswagen","Passat (B1)")]),
("Mazda 121 was a rebadged Fiesta built in Valencia",
 [("Mazda","121"),("Ford","Fiesta (Mk1)")]),
("Type Four platform quartet",
 [("Saab","9000"),("Lancia","Thema"),("Fiat","Croma"),("Alfa Romeo","164")]),
("XM and 605 share the PSA V-platform",
 [("Citroën","XM"),("Peugeot","605")]),
("Peugeot 106 / Citroën Saxo supermini twins",
 [("Peugeot","106"),("Citroën","Saxo")]),
("Ford–VW AutoEuropa MPV program",
 [("Ford","Galaxy"),("SEAT","Alhambra"),("Volkswagen","Sharan")]),
("Captive import twins from Nagoya",
 [("Mitsubishi","3000GT"),("Dodge","Stealth")]),
("GM J-body: the Cimarron was a gilded Cavalier",
 [("Cadillac","Cimarron"),("Chevrolet","Cavalier")]),
("Chrysler K-car twins",
 [("Plymouth","Reliant"),("Dodge","Aries")]),
("Chrysler's original minivan twins on the K-derived S platform",
 [("Dodge","Caravan"),("Plymouth","Voyager")]),
("Project XX: co-developed in the Honda–Rover alliance",
 [("Rover","800"),("Honda","Legend")]),
("Chrysler LX siblings",
 [("Chrysler","300C"),("Dodge","Charger (LX)"),("Dodge","Challenger (2008)")]),
("Hyundai Motor Group E-GMP electric platform",
 [("Hyundai","Ioniq 5"),("Kia","EV6"),("Genesis","GV60")]),
("Y5 platform mid-size twins",
 [("Hyundai","Sonata (YF)"),("Kia","Optima (K5)")]),
("986 and 996 famously shared front structure, lights and interior parts",
 [("Porsche","Boxster (986)"),("Porsche","911 (996)")]),
("Lotus sold the M100 Elan tooling to Kia after production ended",
 [("Kia","Elan"),("Lotus","Elan (M100)")]),
("Quattroporte V and GranTurismo share the M139 platform",
 [("Maserati","Quattroporte V"),("Maserati","GranTurismo")]),
]
