# Makes: name -> (country, founded_year or None)
MAKES = {
    "Toyota": ("Japan", 1937), "Lexus": ("Japan", 1989), "Scion": ("United States", 2003),
    "Subaru": ("Japan", 1953), "Honda": ("Japan", 1948), "Acura": ("United States", 1986),
    "Nissan": ("Japan", 1933), "Infiniti": ("Japan", 1989), "Mazda": ("Japan", 1920),
    "Mitsubishi": ("Japan", 1970), "Suzuki": ("Japan", 1909), "Isuzu": ("Japan", 1916),
    "Daewoo": ("South Korea", 1982), "Hyundai": ("South Korea", 1967),
    "Genesis": ("South Korea", 2015), "Kia": ("South Korea", 1944),
    "Volkswagen": ("Germany", 1937), "Audi": ("Germany", 1909), "Porsche": ("Germany", 1931),
    "BMW": ("Germany", 1916), "Mini": ("United Kingdom", 2000), "Mercedes-Benz": ("Germany", 1926),
    "Smart": ("Germany", 1994), "Opel": ("Germany", 1862),
    "Ford": ("United States", 1903), "Mercury": ("United States", 1938),
    "Chevrolet": ("United States", 1911), "Pontiac": ("United States", 1926),
    "Cadillac": ("United States", 1902), "Saturn": ("United States", 1985),
    "General Motors": ("United States", 1908), "Geo": ("United States", 1989),
    "Holden": ("Australia", 1856), "Dodge": ("United States", 1900),
    "Chrysler": ("United States", 1925), "Plymouth": ("United States", 1928),
    "Eagle": ("United States", 1988), "Jeep": ("United States", 1943),
    "AMC": ("United States", 1954), "Tesla": ("United States", 2003),
    "DMC": ("United States", 1975),
    "Ferrari": ("Italy", 1939), "Lamborghini": ("Italy", 1963), "Maserati": ("Italy", 1914),
    "Alfa Romeo": ("Italy", 1910), "Lancia": ("Italy", 1906), "Fiat": ("Italy", 1899),
    "De Tomaso": ("Italy", 1959), "Pagani": ("Italy", 1992),
    "Lotus": ("United Kingdom", 1952), "Jaguar": ("United Kingdom", 1935),
    "Aston Martin": ("United Kingdom", 1913), "Bentley": ("United Kingdom", 1919),
    "Rolls-Royce": ("United Kingdom", 1904), "McLaren": ("United Kingdom", 1985),
    "Gordon Murray Automotive": ("United Kingdom", 2017),
    "Land Rover": ("United Kingdom", 1948), "Rover": ("United Kingdom", 1904),
    "Triumph": ("United Kingdom", 1885), "Austin": ("United Kingdom", 1905),
    "TVR": ("United Kingdom", 1946),
    "Peugeot": ("France", 1896), "Citroën": ("France", 1919), "Renault": ("France", 1899),
    "Alpine": ("France", 1955), "Bugatti": ("France", 1909),
    "Volvo": ("Sweden", 1927), "Polestar": ("Sweden", 2017), "Saab": ("Sweden", 1945),
    "Koenigsegg": ("Sweden", 1994),
    "SEAT": ("Spain", 1950), "Škoda": ("Czech Republic", 1895),
    "Lada": ("Russia", 1966), "Zastava": ("Serbia", 1953), "FSO": ("Poland", 1951),
    "Lucid": ("United States", 2007), "Rivian": ("United States", 2009),
    "BYD": ("China", 2003), "Xiaomi": ("China", 2021),
    # ---- pre-1959 makes (added when the database's floor moved to 1880) ----
    "Benz": ("Germany", 1883), "Mercedes": ("Germany", 1901),
    "Duesenberg": ("United States", 1913), "Auburn": ("United States", 1900),
    "Cord": ("United States", 1929), "Delahaye": ("France", 1894),
    "Lincoln": ("United States", 1917), "MG": ("United Kingdom", 1924),
    "Cisitalia": ("Italy", 1946), "Morris": ("United Kingdom", 1912),
}

# Designers: name -> (kind, birth, death, country, one-line note)
DESIGNERS = {
    "Giorgetto Giugiaro": ("person", 1938, None, "Italy", "Italdesign founder; Car Designer of the Century (1999)"),
    "Marcello Gandini": ("person", 1938, 2024, "Italy", "Bertone's wedge master — Miura, Countach, Stratos"),
    "Leonardo Fioravanti": ("person", 1938, None, "Italy", "Pininfarina's great Ferrari era — Daytona to F40"),
    "Aldo Brovarone": ("person", 1926, 2020, "Italy", "Pininfarina veteran; shaped the Dino"),
    "Paolo Martin": ("person", 1943, None, "Italy", "Pininfarina — Fiat 130 Coupé, Rolls Camargue"),
    "Ercole Spada": ("person", 1938, 2023, "Italy", "Zagato legend, later BMW and I.DE.A"),
    "Giovanni Michelotti": ("person", 1921, 1980, "Italy", "Prolific freelancer — Triumphs and BMWs"),
    "Tom Tjaarda": ("person", 1934, 2017, "United States", "American in Turin — Pantera and Fiesta alike"),
    "Jason Castriota": ("person", 1974, None, "United States", "Pininfarina — 599 GTB, Maserati GranTurismo"),
    "Ken Okuyama": ("person", 1959, None, "Japan", "Pininfarina design chief — Ferrari Enzo"),
    "Flavio Manzoni": ("person", 1965, None, "Italy", "Ferrari's in-house design era since 2010"),
    "Enrico Fumia": ("person", 1948, None, "Italy", "Pininfarina — Alfa 164 and the 916 twins"),
    "Filippo Perini": ("person", None, None, "Italy", "Lamborghini Centro Stile — Aventador"),
    "Mitja Borkert": ("person", 1974, None, "Germany", "Lamborghini design head since 2016"),
    "Luc Donckerwolke": ("person", 1965, None, "Belgium", "Lamborghini's rebirth, later Genesis"),
    "Walter de Silva": ("person", 1951, None, "Italy", "Alfa 156 to Audi A5 — VW Group design boss"),
    "Wolfgang Egger": ("person", 1963, None, "Germany", "Alfa/Audi, now BYD design director"),
    "Roberto Giolito": ("person", 1962, None, "Italy", "Fiat Multipla and the 2007 500"),
    "Pininfarina": ("studio", 1930, None, "Italy", "Turin's grand carrozzeria — Ferrari's house style"),
    "Bertone": ("studio", 1912, None, "Italy", "Turin studio that launched Giugiaro and Gandini"),
    "Bruno Sacco": ("person", 1933, 2024, "Italy", "Mercedes design 1975–99 — the Sacco era"),
    "Paul Bracq": ("person", 1933, 2024, "France", "Mercedes Pagoda, BMW's early-70s look"),
    "Anatole Lapine": ("person", 1930, 2012, "Latvia", "Porsche design chief — the 928"),
    "Harm Lagaay": ("person", 1946, None, "Netherlands", "Porsche 924, BMW Z1, 90s Porsche revival"),
    "Tony Hatter": ("person", 1954, None, "United Kingdom", "Porsche 993 — the last air-cooled 911"),
    "Pinky Lai": ("person", 1951, None, "Hong Kong", "Porsche 996 — first water-cooled 911"),
    "Grant Larson": ("person", 1957, None, "United States", "Porsche Boxster and Carrera GT"),
    "Michael Mauer": ("person", 1962, None, "Germany", "Mercedes SLK, then Porsche design chief"),
    "Chris Bangle": ("person", 1956, None, "United States", "Fiat Coupé, then BMW's radical 2000s"),
    "Adrian van Hooydonk": ("person", 1964, None, "Netherlands", "BMW design chief after Bangle"),
    "Anders Warming": ("person", 1972, None, "Denmark", "BMW Z4 E85 exterior"),
    "Calvin Luk": ("person", None, None, "Australia", "BMW Z4 G29 exterior"),
    "Richard Kim": ("person", None, None, "United States", "BMW i3 exterior — the i era"),
    "Benoit Jacob": ("person", 1965, None, "France", "BMW i design head — production i8"),
    "Klaus Kapitza": ("person", None, None, "Germany", "BMW 8 Series E31"),
    "Claus Luthe": ("person", 1932, 2008, "Germany", "NSU Ro80, then BMW's 80s canon"),
    "Hartmut Warkuß": ("person", 1940, None, "Germany", "Audi 100 C3 aero era, VW Group design"),
    "Marc Lichte": ("person", 1969, None, "Germany", "Audi design head — e-tron GT"),
    "J Mays": ("person", 1954, None, "United States", "Audi TT concept, Ford's retrofuturism"),
    "Freeman Thomas": ("person", 1957, None, "United States", "Audi TT and New Beetle concepts"),
    "Peter Schreyer": ("person", 1953, None, "Germany", "Audi TT era, then Kia's transformation"),
    "Gregory Guillaume": ("person", None, None, "France", "Kia Europe — Stinger"),
    "Karim Habib": ("person", 1970, None, "Lebanon", "BMW, Infiniti, now Kia design head"),
    "Michael Fink": ("person", None, None, "United States", "Mercedes CLS — the four-door coupé"),
    "Mark Fetherston": ("person", 1976, None, "United Kingdom", "Mercedes SLS AMG and AMG GT"),
    "Erhard Schnell": ("person", 1927, 2020, "Germany", "Opel GT, Manta and Calibra"),
    "Ferdinand Alexander Porsche": ("person", 1935, 2012, "Germany", "'Butzi' — the original 911"),
    "Ian Callum": ("person", 1954, None, "United Kingdom", "Aston DB7, Jaguar's modern era"),
    "Peter Horbury": ("person", 1950, 2023, "United Kingdom", "Volvo's great softening — C70, S80"),
    "Thomas Ingenlath": ("person", 1964, None, "Germany", "Volvo XC90 II, Polestar CEO-designer"),
    "Gordon Murray": ("person", 1946, None, "South Africa", "F1 engineer-auteur — McLaren F1, T.50"),
    "Peter Stevens": ("person", 1943, None, "United Kingdom", "McLaren F1 styling, Elan M100"),
    "Julian Thomson": ("person", 1961, None, "United Kingdom", "Lotus Elise Series 1"),
    "Russell Carr": ("person", None, None, "United Kingdom", "Lotus design head — Evora"),
    "Marek Reichman": ("person", 1966, None, "United Kingdom", "Aston Martin — One-77, DB11"),
    "Henrik Fisker": ("person", 1963, None, "Denmark", "BMW Z8, Aston V8 Vantage, Fisker"),
    "David Bache": ("person", 1925, 1994, "United Kingdom", "Range Rover and Rover SD1"),
    "Harris Mann": ("person", 1938, 2023, "United Kingdom", "British Leyland wedge — TR7"),
    "Roy Axe": ("person", 1937, 2010, "United Kingdom", "Rover 800, Chrysler UK"),
    "Richard Woolley": ("person", None, None, "United Kingdom", "Rover 75"),
    "Gerry McGovern": ("person", 1956, None, "United Kingdom", "Land Rover — Evoque, new Defender"),
    "Giles Taylor": ("person", 1968, None, "United Kingdom", "Rolls-Royce Phantom VIII"),
    "Marek Djordjevic": ("person", None, None, "United States", "Rolls-Royce Phantom VII"),
    "Malcolm Sayer": ("person", 1916, 1970, "United Kingdom", "Aerodynamicist — E-Type, XJS"),
    "William Lyons": ("person", 1901, 1985, "United Kingdom", "Jaguar founder — the XJ line"),
    "Keith Helfet": ("person", 1946, None, "South Africa", "Jaguar XJ220"),
    "Geoff Lawson": ("person", 1944, 1999, "United Kingdom", "Jaguar design chief — XK8"),
    "Alec Issigonis": ("person", 1906, 1988, "United Kingdom", "The Mini"),
    "Robert Opron": ("person", 1932, 2021, "France", "Citroën SM, CX and GS; Alfa SZ sketch"),
    "Gérard Welter": ("person", 1942, 2018, "France", "Peugeot 205 — in-house hero"),
    "Patrick le Quément": ("person", 1945, None, "France", "Renault's bold era — Twingo, Avantime"),
    "Gilles Vidal": ("person", 1972, None, "France", "Peugeot revival, Renault 5 E-Tech"),
    "Antony Villain": ("person", None, None, "France", "Alpine A110 revival"),
    "Michel Boué": ("person", 1936, 1971, "France", "Renault 5 — died before its launch"),
    "Gaston Juchet": ("person", 1925, 2006, "France", "Renault 16 — the first big hatchback"),
    "Antonis Volanis": ("person", 1948, None, "Greece", "Matra — Renault Espace"),
    "Jan Wilsgaard": ("person", 1930, 2016, "Sweden", "Volvo's boxes — 240, 850"),
    "Pelle Petterson": ("person", 1932, None, "Sweden", "Volvo P1800 — yachtsman-designer"),
    "Sixten Sason": ("person", 1912, 1967, "Sweden", "Saab's teardrop line — the 99"),
    "Björn Envall": ("person", 1942, None, "Sweden", "Saab 900"),
    "Larry Shinoda": ("person", 1930, 1997, "United States", "Corvette Mako Shark → C3, Boss 302"),
    "Bill Mitchell": ("person", 1912, 1988, "United States", "GM styling czar 1958–77"),
    "Bill Porter": ("person", 1931, 2025, "United States", "1970 Firebird/Trans Am"),
    "Richard Sias": ("person", 1940, None, "United States", "1968 Charger coke-bottle"),
    "John Herlitz": ("person", 1942, 2008, "United States", "1970 Plymouth 'Cuda"),
    "Carl Cameron": ("person", None, None, "United States", "1970 Dodge Challenger"),
    "Dick Teague": ("person", 1923, 1991, "United States", "AMC's resourceful one — Pacer, XJ Cherokee"),
    "Tom Gale": ("person", 1943, None, "United States", "Chrysler — Viper, cab-forward"),
    "Ralph Gilles": ("person", 1970, None, "United States", "Chrysler 300C"),
    "Bryan Nesbitt": ("person", 1969, None, "United States", "PT Cruiser, Chevy HHR"),
    "Jack Telnack": ("person", 1937, None, "United States", "Ford aero era — Fox Mustang, Taurus"),
    "Uwe Bahnsen": ("person", 1930, 2013, "Germany", "Ford of Europe — Sierra"),
    "Claude Lobo": ("person", 1943, 2019, "France", "Ford New Edge — Ka, Focus"),
    "Gale Halderman": ("person", 1932, 2020, "United States", "1964½ Mustang body"),
    "Sid Ramnarace": ("person", None, None, "Canada", "2005 retro Mustang"),
    "Camilo Pardo": ("person", 1966, None, "United States", "2005 Ford GT"),
    "Franz von Holzhausen": ("person", 1968, None, "United States", "Pontiac Solstice, then all core Teslas"),
    "Michael Simcoe": ("person", 1959, None, "Australia", "Holden Monaro, GM design head"),
    "SangYup Lee": ("person", 1969, None, "South Korea", "Camaro, Bentley, Hyundai/Genesis chief"),
    "Shiro Nakamura": ("person", 1950, None, "Japan", "Nissan design chief — GT-R era"),
    "Ajay Panchal": ("person", None, None, "United Kingdom", "Nissan 350Z exterior"),
    "Yoshihiko Matsuo": ("person", 1933, 2020, "Japan", "Datsun 240Z"),
    "Tom Matano": ("person", 1947, None, "Japan", "Mazda USA — MX-5 Miata"),
    "Masashi Nakayama": ("person", None, None, "Japan", "MX-5 ND chief designer"),
    "Matasaburo Maeda": ("person", None, None, "Japan", "First RX-7; father of Ikuo"),
    "Ikuo Maeda": ("person", 1959, None, "Japan", "RX-8, Mazda Kodo design era"),
    "Satoru Nozaki": ("person", None, None, "Japan", "Toyota 2000GT"),
    "Sotiris Kovos": ("person", None, None, "Greece", "First Toyota Yaris"),
    "Mike Torpey": ("person", None, None, "United States", "Kia Soul concept"),
    "Simon Cox": ("person", 1961, None, "United Kingdom", "Isuzu VehiCROSS"),
    "Dirk van Braeckel": ("person", 1958, None, "Belgium", "Škoda revival, Bentley Continental GT"),
    "Jozef Kabaň": ("person", 1973, None, "Slovakia", "Bugatti Veyron"),
    "Achim Anscheidt": ("person", 1962, None, "Germany", "Bugatti Chiron"),
    "Christian von Koenigsegg": ("person", 1972, None, "Sweden", "Founder-designer of the CC8S"),
    "Horacio Pagani": ("person", 1955, None, "Argentina", "Zonda and Huayra"),
    "Derek Jenkins": ("person", None, None, "United States", "Lucid Air"),
    "William Towns": ("person", 1936, 1993, "United Kingdom", "Aston wedge — Lagonda"),
    "Frank Stephenson": ("person", 1959, None, "United States", "New Mini, Ferrari F430, McLaren 12C and P1"),
    "Wayne Cherry": ("person", 1937, None, "United States", "GM design VP — Art & Science Cadillacs"),
    "Martin Smith": ("person", 1949, None, "United Kingdom", "Audi Quattro; later Ford's kinetic design"),
}
